### ISSUE TITLE
(SPOILERS) Add hint to (SPOILERS)

### ISSUE THREAD

**Issue by hearth1an** [hearth1an/hearth1an.ChristmasStory#17]
Once player find correct symbols to disable the light on the third bridge in Dream World, there should be a hint  (like when player standing near the coordinates panel in the nomai vessel)

**Comment by hearth1an** [comment]
promt added, need to make trigger and fix positioning

**Comment by xen-42** [comment]
I made the volume and fixed the positioning. It appears now when they are beside the totem. All that's missing is only adding it once they have found the symbols

**Comment by hearth1an** [comment]
done + made it translatable
