### ISSUE TITLE
Scout crystal shows up on camera

### ISSUE THREAD

**Issue by xen-42** [hearth1an/hearth1an.ChristmasStory#20]
We could do something with layers to fix this

**Comment by hearth1an** [comment]
Need to check if this still exists

**Comment by hearth1an** [comment]
![image](https://user-images.githubusercontent.com/106444732/232606946-05387859-d082-4d92-8bb6-6b38414e14f6.png)
this thing, not grav crystal

**Comment by hearth1an** [comment]
probably happening bc of disabling Rudolfo

**Comment by hearth1an** [comment]
Happening on entering the DB_ClusterDimension_Body

**Comment by hearth1an** [comment]
idk what we can do with it
