### ISSUE TITLE
Screen-space reflection issue

### ISSUE THREAD

**Issue by misternebula** [hearth1an/hearth1an.ChristmasStory#26]
![image](https://user-images.githubusercontent.com/41904486/231572337-e4192d28-c3c2-491e-b63f-4a03bec96fce.png)

**Comment by xen-42** [comment]
What does that mean

**Comment by misternebula** [comment]
look at the ice - you can see the grass underneath it

**Comment by misternebula** [comment]
![image](https://user-images.githubusercontent.com/41904486/231578456-a261368a-5841-4398-b80a-2d0915ed7b62.png)

**Comment by hearth1an** [comment]
I assume it should be inverted instead. This is the shader from bramble crater ice pieces bc interloper ice don't have reflection at all. Will see if there's shader that could fit better (not sure if I can make my own)

**Comment by hearth1an** [comment]
![image](https://user-images.githubusercontent.com/106444732/231661116-9ed8312c-5a58-4ae3-9f1d-29d8119e363d.png)
here's the other option with no reflection at all, looks nice too

**Comment by hearth1an** [comment]
will do nothing with it
