### ISSUE TITLE
Activating dialogue while eye close is happening results in a softlock

### ISSUE THREAD

**Issue by misternebula** [hearth1an/hearth1an.ChristmasStory#28]
![image](https://user-images.githubusercontent.com/41904486/231573970-5ec3a052-0b24-4b79-b0c2-c51675d630e7.png)

**Comment by hearth1an** [comment]
This happened bc it's a base game dialogue, all objects related to this dialogue are disabled so I'm just removing her (forgot to do it before. Thank you for report!

**Comment by hearth1an** [comment]
And fixed dialogue for Tuff too!
