### ISSUE TITLE
Chert doesn't consider the broken vessel warp core an interesting artefact

### ISSUE THREAD

**Issue by misternebula** [hearth1an/hearth1an.ChristmasStory#31]

**Comment by hearth1an** [comment]
Just a piece of broken metal!

**Comment by misternebula** [comment]
but they said they wanted to see a previously unseen nomai artefact - one from the unknown vessel would count, wouldnt it?

**Comment by hearth1an** [comment]
not sure about that. hearthians doesn't know about modern nomai and how their tech is look like, so they wouldn't recognise it as a nomai tech at all. seems logical to me

**Comment by solitary-sails** [comment]
btw, Chert doesn't consider lamp form stranger.

**Comment by hearth1an** [comment]
> 

that's intended
