### ISSUE TITLE
About learn meditation

### ISSUE THREAD

**Issue by solitary-sails** [hearth1an/hearth1an.ChristmasStory#41]
Is there any method to learn meditate from Gabbro since I'm play with a new profile ?I sent him back to the village, but still couldn't learn meditation from him after several loop. Does this mod change the method of learning meditation or is it just a bug?

**Comment by hearth1an** [comment]
Hmm there's no way to learn meditation yet, but yeah I feel like it's wrong to cut this feature. I'll just add a dialogue to Gabbro to let player learn how to meditate.

**Comment by hearth1an** [comment]
Done in v1.0.1, update should be live soon, thx for suggestion!
