### ISSUE TITLE
Two Feldspar

### ISSUE THREAD

**Issue by solitary-sails** [hearth1an/hearth1an.ChristmasStory#43]
There is another Feldspar in Dark Bramble after I sent him back to village.
![图片](https://github.com/hearth1an/hearth1an.ChristmasStory/assets/52939914/d4696737-1668-4cde-bec8-f2ab0a96ac25)
![F1](https://github.com/hearth1an/hearth1an.ChristmasStory/assets/52939914/5aa8d81c-6c58-404a-ab10-071fb3896ef1)

**Comment by solitary-sails** [comment]
The location of the extra feldspar is on the eggs of the anglerfish.

**Comment by hearth1an** [comment]
Thanks for report, fixed in last update
