### ISSUE TITLE
Maybe a typo?

### ISSUE THREAD

**Issue by solitary-sails** [hearth1an/hearth1an.ChristmasStory#44]
I'm working on translate to Chinese and I kinda wonder if this is a typo?
![图片](https://github.com/hearth1an/hearth1an.ChristmasStory/assets/52939914/fc8570b2-ddda-4569-aa1d-18bc5a8bb76e)

**Comment by hearth1an** [comment]
Player gets such option if trying to get any ship traveler but the ship is broken. It's kinda rare, but still should exist

**Comment by solitary-sails** [comment]
I mean, why is it "not broken" here, not "broken" or "not functioning" like other travelers

**Comment by hearth1an** [comment]
Oh, yeah. Sure, there should be no "not". Thx for report!

**Comment by solitary-sails** [comment]
I finished the Chinese translation, but I also found other possible typo( RADIO_START_19 ). Please confirm, I will modify the translation according to your confirmation results before submit a pull request.

**Comment by hearth1an** [comment]
yeah it should be just
"RADIO_START_19": "Thank you, Gossan!",

**Comment by solitary-sails** [comment]
Thanks, I got it
