### ISSUE TITLE
Missed sentence in translation file

### ISSUE THREAD

**Issue by solitary-sails** [hearth1an/hearth1an.ChristmasStory#46]
Although not an important sentence, I found a sentence that was not included in the translation file.
![Missed_sentence](https://github.com/hearth1an/hearth1an.ChristmasStory/assets/52939914/457794f2-b837-4c88-8c70-ee80367e2810)

**Comment by hearth1an** [comment]
Hm, interesting. Thx for report! Will take  a look

**Comment by hearth1an** [comment]
All good in english translation file 
![image](https://github.com/hearth1an/hearth1an.ChristmasStory/assets/106444732/3fa2385f-e806-4670-b2ac-496e37091353)

**Comment by solitary-sails** [comment]
I mean there is no key-value pair for "Sure!".

**Comment by hearth1an** [comment]
Oh I see. Can you type how it will be in Chinese? I'll add it manually

**Comment by solitary-sails** [comment]
It will be "当然！"

**Comment by hearth1an** [comment]
aight will be added in next update
