### ISSUE TITLE
Music ensemble issues

### ISSUE THREAD

**Issue by nice2cu1** [hearth1an/hearth1an.ChristmasStory#49]
No matter who I'm talking to, once I end the conversation, it causes the ensemble to start all over again

**Comment by hearth1an** [comment]
You mean any dialogue resets travelers music in the Village?

**Comment by nice2cu1** [comment]
@hearth1an yes

**Comment by hearth1an** [comment]
@nice2cu1 are you using time freeze in dialogues?

**Comment by nice2cu1** [comment]
@hearth1an yes

**Comment by hearth1an** [comment]
@nice2cu1 alright, this is just how signals work, same with vanilla. time freezing or pausing the game will reset signals. you can disable time freeze in dialogues to prevent this.
